backend:
  name: git-gateway
  branch: master # or main, depending on your repo
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
